# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
    imports =
        [ (modulesPath + "/installer/scan/not-detected.nix")
        ];

    boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" ];
    boot.initrd.kernelModules = [ ];
    boot.kernelModules = [ "kvm-intel" ];
    boot.extraModulePackages = [ ];

    fileSystems."/" =
    { device = "/dev/disk/by-uuid/06b7aaf3-bfdc-4e4f-a903-2da3cdae5b23";
        fsType = "ext4";
    };

    fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/0DE1-CF91";
        fsType = "vfat";
    };

    swapDevices =
        [ { device = "/dev/disk/by-uuid/599b1b5d-2b29-4123-99ec-60febc6176e3"; }
        ];

# Intel Graphics
        hardware.opengl.extraPackages = [
            pkgs.intel-compute-runtime
                pkgs.intel-media-driver
        ];


# Nvidia Drivers
# Making sure to use the proprietary drivers until the issue above is fixed upstream
# boot.kernelParams = [ "nvidia.NVreg_PreserveVideoMemoryAllocations=1" ];
        hardware.opengl = {
            enable = true;
            driSupport = true;
            driSupport32Bit = true;
        };
        services.xserver.videoDrivers = [ "nvidia" ];

        hardware.nvidia = {
            modesetting.enable = true;
            powerManagement.enable = false;
            powerManagement.finegrained = false;
            open = false;
            nvidiaSettings = true;
            package = config.boot.kernelPackages.nvidiaPackages.beta;

            prime = {
                intelBusId = "PCI:00:02:0";
                nvidiaBusId = "PCI:01:00:0";


# Sync Mode vs Offload Mode

# sync.enable = true;

                offload = {
                    enable = true;
                    enableOffloadCmd = true;
                };
            };
        };

# Enables DHCP on each ethernet and wireless interface. In case of scripted networking
# (the default) this is the recommended approach. When using systemd-networkd it's
# still possible to use this option, but it's recommended to use it in conjunction
# with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
        networking.useDHCP = lib.mkDefault true;
# networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

        nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
        hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
